fprintf(1,'Executing %s at %s:\n',mfilename,datestr(now));
ver,
try,
        %% Generated by nipype.interfaces.spm
        if isempty(which('spm')),
             throw(MException('SPMCheck:NotFound', 'SPM not in matlab path'));
        end
        [name, version] = spm('ver');
        fprintf('SPM version: %s Release: %s\n',name, version);
        fprintf('SPM path: %s\n', which('spm'));
        spm('Defaults','fMRI');

        if strcmp(name, 'SPM8') || strcmp(name, 'SPM12b'),
           spm_jobman('initcfg');
           spm_get_defaults('cmdline', 1);
        end

        jobs{1}.spm.spatial.coreg.estimate.roptions.prefix = 'r';
jobs{1}.spm.spatial.coreg.estimate.source = {...
['/Users/kastman/code/ofmri-ds107/sub001/basic_example/nipype-workingdir/spm_preproc/coregister/meanbold_run1.img'];...
};
jobs{1}.spm.spatial.coreg.estimate.other = {...
'/Users/kastman/code/ofmri-ds107/sub001/basic_example/nipype-workingdir/spm_preproc/coregister/bold_run1.img';...
'/Users/kastman/code/ofmri-ds107/sub001/basic_example/nipype-workingdir/spm_preproc/coregister/bold_run2.img';...
};
jobs{1}.spm.spatial.coreg.estimate.ref = {...
['/Users/kastman/code/ofmri-ds107/sub001/basic_example/nipype-workingdir/spm_preproc/coregister/highres001.img'];...
};

        spm_jobman('run', jobs);

        
,catch ME,
fprintf(2,'MATLAB code threw an exception:\n');
fprintf(2,'%s\n',ME.message);
if length(ME.stack) ~= 0, fprintf(2,'File:%s\nName:%s\nLine:%d\n',ME.stack.file,ME.stack.name,ME.stack.line);, end;
end;